name: kosankuy
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dotted_border: ^2.0.0+3
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_icons: ^1.1.0
  flutter_launcher_icons: ^0.11.0
  flutter_map: ^3.0.0
  get: ^4.6.5
  google_fonts: ^3.0.1
  intl: ^0.17.0
  location: ^4.4.0
  mapbox_gl: ^0.16.0
  mask_text_input_formatter: ^2.4.0
  shared_preferences: ^2.0.15
  signature: ^5.3.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ic_launcher.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/ic_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
